name: Ecommerce-fun CI/CD

on:
  pull_request:
    types: [closed]
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run linting
        run: npm run lint || echo "No linting configured"

      - name: Run tests
        run: npm run test:ci

      - name: Build project
        run: npm run build:ci
