name: Ecommerce-fun Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master, develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Build project
        run: npm run build:ci
