name: MegaMart Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npx prettier --check "src/**/*.{js,jsx,json,css,md}"

  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      - name: Check test coverage
        run: |
          COVERAGE=$(npx jest --coverage --ci --json | jq -r '.coverageMap.total.statements.pct')
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Test coverage is below 70%: $COVERAGE%"
            exit 1
          else
            echo "Test coverage is sufficient: $COVERAGE%"
          fi

  bundle-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Analyze bundle size
        uses: actions/upload-artifact@v3
        with:
          name: bundle-report
          path: build/
          retention-days: 7
