name: Ecommerce-fun Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master, develop]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Setup Steelheart AI
        run: |
          chmod +x setup_steelheart.sh
          ./setup_steelheart.sh

      - name: Run auto-review with Steelheart
        run: npx steelheart auto-review

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:ci

      - name: Build project
        run: npm run build:ci
